[all]
node1 	 ansible_host=192.168.1.99 ip=192.168.1.99
node2 	 ansible_host=192.168.1.100 ip=192.168.1.100
node3 	 ansible_host=192.168.1.102 ip=192.168.1.102

[kube-master]
node1 	 

[kube-node]
node1 	 
node2 	 
node3 	 

[etcd]
node1 	 
node2 	 
node3 	 

[k8s-cluster:children]
kube-node 	 
kube-master 	 

[calico-rr]

